[package]
name = "rust_test_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "16.1.0"

[[bin]]
name = "rust_test_binary"  # Replace with your binary's name
path = "src/main.rs"